[package]
name = "gptman"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
bincode = "1.0.1"
serde_derive = "1.0.83"
serde = "1.0.83"
crc = "1.0.0"
log = "0.4.0"
env_logger = "0.6.0"
ansi_term = "0.11"
pad = "0.1"
unicode-width = "0.1.5"
clap = "2.32"
linefeed = "0.5"
nix = "0.12.0"
